name    'panaceya-dhcp'
version '1.0.1'
source 'git://github.com/panaceya/puppet-dhcp'
author 'ZLeslie, theforeman, ThePanaceya'
license 'Apache License Version 2.0'
summary 'Manage the ISC DHCP Daemon'
description 'A Puppet module to deploy and manage the ISC DHCP server.'
project_page 'http://github.com/panaceya/puppet-dhcp'
dependency 'theforeman/concat_native', '>= 1.3.0'
